package gui;

import model.Notification;
import model.User;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

public class NotificationPanel extends JPanel {
    private static final long serialVersionUID = 1L;

    private MainFrame mainFrame;
    private DefaultTableModel tableModel;

    public NotificationPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        setLayout(new BorderLayout(15, 15));
        setBorder(new EmptyBorder(15, 15, 15, 15));
        initUI();
    }

    private void initUI() {
        // Info Banner
        JPanel infoCard = new JPanel(new BorderLayout());
        infoCard.setBorder(BorderFactory.createTitledBorder("System Notifications Center"));
        JLabel infoLabel = new JLabel("<html>Notifications are automatically generated by the system when transactions occur, budgets are exceeded, or savings milestones are achieved.</html>");
        infoLabel.setFont(Theme.BODY_FONT);
        infoLabel.setBorder(new EmptyBorder(8, 10, 8, 10));
        infoCard.add(infoLabel, BorderLayout.CENTER);

        add(infoCard, BorderLayout.NORTH);

        // Notifications Table
        tableModel = new DefaultTableModel(new Object[]{"ID", "Notification Type", "System Message", "Status", "Created At"}, 0);
        JTable table = new JTable(tableModel);

        JPanel centerPanel = new JPanel(new BorderLayout(5, 5));
        centerPanel.add(new JScrollPane(table), BorderLayout.CENTER);

        JPanel bottomBtnPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT, 12, 0));
        JButton readBtn = UIHelper.createBlueButton("Mark Selected as Read");
        readBtn.addActionListener(e -> handleMarkRead(table));

        JButton deleteNotifBtn = UIHelper.createBlueButton("Delete Notification");
        deleteNotifBtn.addActionListener(e -> handleDeleteNotification(table));

        bottomBtnPanel.add(readBtn);
        bottomBtnPanel.add(deleteNotifBtn);

        centerPanel.add(bottomBtnPanel, BorderLayout.SOUTH);
        add(centerPanel, BorderLayout.CENTER);
    }

    public void refreshData() {
        User user = mainFrame.getCurrentUser();
        if (user == null) return;

        List<Notification> notifications = mainFrame.getNotificationService().getUserNotifications(user.getUserId());
        tableModel.setRowCount(0);
        for (Notification n : notifications) {
            tableModel.addRow(new Object[]{
                    n.getNotificationId(),
                    n.getNotificationType(),
                    n.getMessage(),
                    n.isReadStatus() ? "READ" : "UNREAD",
                    n.getCreatedAt().toString()
            });
        }
    }

    private void handleMarkRead(JTable table) {
        int selectedRow = table.getSelectedRow();
        if (selectedRow == -1) {
            UIHelper.showWarning(this, "Please select a notification from the table.");
            return;
        }
        int notifId = (int) table.getValueAt(selectedRow, 0);
        try {
            Notification n = mainFrame.getNotificationService().getNotificationById(notifId);
            if (n != null) {
                mainFrame.getNotificationService().markAsRead(n);
                mainFrame.refreshAllPanels();
            }
        } catch (Exception ex) {
            UIHelper.showError(this, "Error marking notification read: " + ex.getMessage());
        }
    }

    private void handleDeleteNotification(JTable table) {
        int selectedRow = table.getSelectedRow();
        if (selectedRow == -1) {
            UIHelper.showWarning(this, "Please select a notification from the table.");
            return;
        }
        int notifId = (int) table.getValueAt(selectedRow, 0);
        try {
            mainFrame.getNotificationService().deleteNotification(notifId);
            mainFrame.refreshAllPanels();
        } catch (Exception ex) {
            UIHelper.showError(this, "Error deleting notification: " + ex.getMessage());
        }
    }
}
